### PR TITLE
email addresses in the README.md have to be in quotes ""

### PR DESCRIPTION
**Pull request by joanwa**
otherwise github assumes this is a webpage. Furthermore added a link to
the mailing list subscription page at sourceforge

### CODE REVIEW

**Comment by langner** [comment]
The 2D potential scan already went in as a regression test in cclib/cclib#25 - thanks for the file. I don't think we need the changes in the README file you propose.

**Comment by joanwa** [comment]
did actually anyone ever click on the link? If you click on it it points to

https://github.com/cclib/cclib/blob/master/cclib-users@lists.sourceforge.net <https://github.com/cclib/cclib/blob/master/cclib-users@lists.sourceforge.net>

which obviously can’t exist. Why would anyone want to leave this as is?

**Comment by langner** [comment]
My apologies, you are right. Could modify the PR to just have those changes then?

**Comment by joanwa** [comment]
sure! you mean to just correct the email address link, without adding the link to the mailing list subscription site? And shall I modify it, or you do it? Was not clear from your email ;)

**Comment by langner** [comment]
I meant: could you do it? :D

**Comment by joanwa** [comment]
is changed!

**Comment by langner** [comment]
There's a also a binary (comrpessed log) file there... can you get rid of that?

**Comment by joanwa** [comment]
closing this pull request because of the binary file, opened another one with just README.md updated

**Pull request closed without merging**
