### PR TITLE
Parses NMR for ORCA.

### PR DESCRIPTION
**Pull request by jevandezande**
Reference implementation of NMR parsing for issue #125 about how to design the NMR attribute.

TODO
----
- [x] Write tests

### CODE REVIEW

**Comment by langner** [comment]
@ATenderholt @berquist I am curious about your opinion here, since I don't have much experience with NMR. Is it reasonable to assume isotropic and anisotropic shifts will always be calculated?

**Comment by langner** [comment]
I'm going to push this one back to v1.5.3 right away.

**Comment by berquist** [comment]
> Is it reasonable to assume isotropic and anisotropic shifts will always be calculated?

Yes, since they are trivial to calculate from the full 3 by 3 tensor. The most important thing is that the full tensor is parsed.

If we're going to use the tuple approach, then the full tensor should be included, but maybe as the last element of the 3; I need to check that all programs actually print the full tensor.

**Comment by langner** [comment]
> > Is it reasonable to assume isotropic and anisotropic shifts will always be calculated?
>
> Yes, since they are trivial to calculate from the full 3 by 3 tensor. The most important thing is that the full tensor is parsed.
> 
> If we're going to use the tuple approach, then the full tensor should be included, but maybe as the last element of the 3; I need to check that all programs actually print the full tensor.

In that case I would prefer to just parse the full tensor and provide a method to extract the other things, if it is trivial.

**Comment by langner** [comment]
@jevandezande Do you think you could modify you code to parse just the full tensor? We can add some additional methods/properties for extracting the parts you're interested in.

**Comment by langner** [comment]
I think it's the full tensor now? Changes need to be reworked after recent refactoring. Also, ideally we'd have two PRs:
1. Adding the attribute itself (no parsing) as a first step, so we get that part down.
2. Adding the implementation for each particular program.

**Comment by langner** [comment]
> I think it's the full tensor now? Changes need to be reworked after recent refactoring. Also, ideally we'd have two PRs:
> 
> 1. Adding the attribute itself (no parsing) as a first step, so we get that part down.
> 2. Adding the implementation for each particular program.

@berquist Do you think this is a good summary of what needs to be done here?

**Comment by langner** [comment]
Talked this over and we should have merged in. @berquist wanted to take a look first.

**Review by langner — APPROVED** [review]

**Review by berquist — APPROVED** [review]
I think this is a fine start, and any real changes can wait for cclib 2.0.

I've made another branch that rebases this on top of current master and has a fix for some metadata issues with the NMR output.

**Comment by berquist** [comment]
Closing in favor of #1002.

**Pull request closed without merging**
