### PR TITLE
Fill an empty polarizability diplen array with np.nan values

### PR DESCRIPTION
**Pull request by xymaxim**

### CODE REVIEW

**Comment by langner** [comment]
It'd be great if we could reproduce this problem and add a test to make sure it stays fixed. Do you have something at hand?

**Comment by berquist** [comment]
It could be adding `Trp_polar_response_diplnx.out` to regressions and comparing to one of the other DALTON polarizability outputs there, all of which have the full tensor.

**Comment by xymaxim** [comment]
Agreed. I'll take care of it. @berquist have reasonably pointed out about filling the missing values with  `np.nan`. And it should be conventional. Since this issue only refers to programs that provide ability to selectively calculate a tensor components, would it be superfluous to enlarge this pull request for other parsers?

**Comment by berquist** [comment]
> Since this issue only refers to programs that provide ability to selectively calculate a tensor components, would it be superfluous to enlarge this pull request for other parsers?

Searching for `empty` returns the matches in ADF and DALTON, plus GAMESS and Q-Chem, but not all for polarizabilities. It should be fine to add this in all cases.

**Comment by xymaxim** [comment]
ADF parser doesn't experience the issue #420 since the ADF program sets the missing components to zero and print these values in matrix format. In this case, should I add a test for ADF parser to ensure that  `np.nan` values are correctly replaced? If so, there was a discussion about standardized inputs and I'm wondering if there are any requirements at the moment (especially for xc-functional)?

**Comment by langner** [comment]
> ADF parser doesn't experience the issue #420 since the ADF program sets the missing components to zero and prints these values in matrix format. In this case, should I add a test for ADF parser to ensure that np.nan values are correctly replaced?

No, I think we should stick to parsing the values that the program prints. Even if those values are not what we would expect based on the method/theory.

**Pull request merged**
