### PR TITLE
Update copyright year to 2017

### PR DESCRIPTION
**Pull request by berquist**
Only 7 months or so late...

Also changes a version number to 1.5.1 in `src/cclib/__init__.py`

### CODE REVIEW

**Comment by langner** [comment]
I dunno... aren't we supposed to have the first year of publication here? https://softwareengineering.stackexchange.com/questions/130478/what-copyright-date-for-an-update-to-an-open-source-project-from-last-year

**Comment by berquist** [comment]
At some point they were all changed over from that format: 1a2a2f22

**Comment by langner** [comment]
> At some point they were all changed over from that format: 1a2a2f2

I know. What do you think we should do?

**Comment by berquist** [comment]
According to that thread, it isn't even required to have that notification there with the date, but I don't think we should remove it completely.

I have no preference for either of:

1. The current year
2. The year when the file was created - the current year

It probably isn't worthwhile to go back to comma-separated years, where only the years the files were modified are present. That's what `git blame` is for.

**Comment by langner** [comment]
> According to that thread, it isn't even required to have that notification there with the date, but I don't think we should remove it completely.
> 
> I have no preference for either of:
> 
> The current year
> The year when the file was created - the current year
> It probably isn't worthwhile to go back to comma-separated years, where only the years the files were modified are present. That's what git blame is for.

I'm fine with what you did.

**Pull request merged**
