### PR TITLE
NWChem: copy over newest data inputs and outputs before running 7.0

### PR DESCRIPTION
**Pull request by berquist**
The first part of #1131, which just adds the new test data. It is not tested yet because at least geometry optimization results in a hard crash. A separate PR will add entries to `testdata` and whatever fixes are necessary to get the tests passing. Another PR after that will clean up the old NWChem versions and move them to regressions.
```
** basicNWChem7.0/dvb_gopt_hf.out: Customized restricted single point HF unittest ***
[NWChem /home/eric/development/cclib_berquist/data/NWChem/basicNWChem7.0/dvb_gopt_hf.out ERROR] Encountered error when parsing.
[NWChem /home/eric/development/cclib_berquist/data/NWChem/basicNWChem7.0/dvb_gopt_hf.out ERROR] Last line read:   no constraints, skipping    0.0000000000000000

Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/miniconda3-4.7.12/envs/cclib_berquist_37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/eric/.pyenv/versions/miniconda3-4.7.12/envs/cclib_berquist_37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/eric/development/cclib_berquist/test/test_data.py", line 337, in <module>
    test_all(parsers, modules, terse=args.terse, silent=args.silent, loglevel=loglevel, summary=True, visual_tests=True)
  File "/home/eric/development/cclib_berquist/test/test_data.py", line 302, in test_all
    errors_or_failures = data_suite.testall()
  File "/home/eric/development/cclib_berquist/test/test_data.py", line 183, in testall
    datatype=test.datatype if hasattr(test, 'datatype') else None
  File "/home/eric/development/cclib_berquist/test/test_data.py", line 115, in getdatafile
    data = logfile.parse()
  File "/home/eric/development/cclib_berquist/cclib/parser/logfileparser.py", line 321, in parse
    self.extract(inputfile, line)
  File "/home/eric/development/cclib_berquist/cclib/parser/nwchemparser.py", line 124, in extract
    assert "maximum gradient threshold" in line
AssertionError
```

### CODE REVIEW

**Comment by berquist** [comment]
> A separate PR will add entries to testdata and whatever fixes are necessary to get the tests passing.

I did need to make one small code change to get the slightly newer vibrational frequency output working, which was already there in some form for 7.0.

**Comment by langner** [comment]
> > A separate PR will add entries to testdata and whatever fixes are necessary to get the tests passing.
> 
> I did need to make one small code change to get the slightly newer vibrational frequency output working, which was already there in some form for 7.0.

Was something failing there before?

**Comment by berquist** [comment]
It looks like the output file from the calculation I ran is just...missing a huge chunk in the middle (all of SCF) and gets cut off in a weird location. It was failing because of an unnecessary check if the SCF energy was there before parsing ZPVE, and it wasn't. I've just tried rerunning it again and...it's still missing. Maybe something is wrong with my NWChem copy...

**Comment by shivupa** [comment]
> It looks like the output file from the calculation I ran is just...missing a huge chunk in the middle (all of SCF) and gets cut off in a weird location. It was failing because of an unnecessary check if the SCF energy was there before parsing ZPVE, and it wasn't. I've just tried rerunning it again and...it's still missing. Maybe something is wrong with my NWChem copy...

What file was this for specifically? I ran `dvb_sp_hf.out` and I didn't see anything missing in the diff wrt your output and wrt to nwchem6.5

**Review by shivupa — APPROVED** [review]

**Comment by amandadumi** [comment]
This pull request in general looks great, thanks! Though, I want to make sure I understand. Shiv's files and yours produce the same output, so the nwchem parser was changed at 1148 to account for this variation in output by removing the unnecessary check on the SCF energy?

**Comment by berquist** [comment]
> This pull request in general looks great, thanks! Though, I want to make sure I understand. Shiv's files and yours produce the same output, so the nwchem parser was changed at 1148 to account for this variation in output by removing the unnecessary check on the SCF energy?

Yes

**Review by amandadumi — APPROVED** [review]

**Comment by berquist** [comment]
Hi Matt, this wasn't resolved, so thanks for the reminder. I'll try and get to it in the next day or two unless you already have a patch.

**Comment by mkhorton** [comment]
Amazing, thanks for the update @berquist! :)

**Pull request merged**
