### PR TITLE
Change the default loglevel to logging.ERROR

### LINKED ISSUE #722: Large number of logging messages printed
Hi,

In version `1.6.1`, when parsing an output file, I get a large number of `INFO` level logging messages printed. I have tested this in `1.5.3` and this does not happen.

I have tested this on the ORCA 4.1 test file [`dvb_sp.out`](../blob/master/data/ORCA/basicORCA4.1/dvb_sp.out) but this is the case for Gaussian and Q-Chem also.

```
Python 3.4.6 (default, Mar 22 2017, 12:26:13) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cclib
>>> cclib.io.ccread('dvb_sp.out')
<cclib.parser.data.ccData_optdone_bool object at 0x2b255c7f0f60
```

```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cclib
>>> cclib.io.ccread('dvb_sp.out')
[ORCA dvb_sp.out INFO] Creating attribute metadata: {}
[ORCA dvb_sp.out INFO] Creating attribute charge: 0
...
[ORCA dvb_sp.out INFO] Creating attribute coreelectrons[]
<cclib.parser.data.ccData_optdone_bool object at 0x114f14e80>
```

I have only been able to test these on two different machines running different versions of python; however, [this google colab notebook](https://colab.research.google.com/drive/13_KA4t47QLZlQdu4U4fPURLTNoL07wPT) demonstrates the same issue.

Using the `logging` module, we can check on `1.6.1` to verify that the logging level is correct.
```
>>> import logging
>>> logging.getLogger('cclib')
<Logger cclib (WARNING)>
```

I have tried changing the logging level using
```
>>> logging.getLogger('cclib').setLevel(logging.ERROR)
>>> logging.getLogger('cclib')
<Logger cclib (ERROR)>
>>> cclib.io.ccread('dvb_sp.out')
[ORCA dvb_sp.out INFO] Creating attribute metadata: {}
[ORCA dvb_sp.out INFO] Creating attribute charge: 0
...
[ORCA dvb_sp.out INFO] Creating attribute coreelectrons[]
<cclib.parser.data.ccData_optdone_bool object at 0x11469aa90>
```

or other levels, but this does nothing.

Furthermore, changing the basic config level _increases_ the number of messages 
```
>>> logging.basicConfig(level=logging.ERROR)
>>> cclib.io.ccread('dvb_sp.out')
[ORCA dvb_sp.out INFO] Creating attribute metadata: {}
INFO:ORCA dvb_sp.out:Creating attribute metadata: {}
[ORCA dvb_sp.out INFO] Creating attribute charge: 0
INFO:ORCA dvb_sp.out:Creating attribute charge: 0
...
[ORCA dvb_sp.out INFO] Creating attribute coreelectrons[]
INFO:ORCA dvb_sp.out:Creating attribute coreelectrons[]
<cclib.parser.data.ccData_optdone_bool object at 0x1146b2a20>
```

This change cannot be reverted unless you close the session.

I am very confused as to what is happening here.

### PR DESCRIPTION
**Pull request by berquist**
Closes #722.

### CODE REVIEW

**Comment by ATenderholt** [comment]
Is there a plan for switching back to WARNING after the false positives you mentioned have been fixed?

**Comment by langner** [comment]
> Is there a plan for switching back to WARNING after the false positives you mentioned have been fixed?

Don't know what @berquist is thinking, but I don't think we have a concrete plan to fix the false positives so I wouldn't bet on it.

**Comment by berquist** [comment]
I hadn't thought about it. Most of the warnings seemed to originate from changing attribute values during geometry optimizations, etc. I've made https://github.com/cclib/cclib/issues/734 so it can be tracked, unless you'd like me to figure it out for this PR.

**Comment by ATenderholt** [comment]
Tracking in another issue sounds good to me.

**Pull request merged**
