### PR TITLE
Change PeriodicTable class to use periodictable library (#604)

### PR DESCRIPTION
**Pull request by pandaxtc**
Change parser.utils.PeriodicTable class to use periodictable library, as per #604. The interface for the class remains unchanged.

### CODE REVIEW

**Comment by pandaxtc** [comment]
@berquist added!

**Comment by berquist** [comment]
Are we testing that the zeroth element is `None`?

**Comment by pandaxtc** [comment]
That was just the behavior of the previous implementation, I can add a test for this in `testutils.py` if you want.

**Comment by berquist** [comment]
Yeah, just so that it makes noise if we ever decide to change the implementation. It can be an `assertNone` under `test_elements`.

**Comment by berquist** [comment]
Thank you!

**Pull request merged**
