### PR TITLE
Q-Chem: feature parity with other parsers

### PR DESCRIPTION
**Pull request by berquist**
This should bring the Q-Chem parser up to feature parity with most of the other parsers; this adds `gbasis`, `aonames`, `atombasis`, and `mocoeffs`.

Question: what should the copyright years be on our source code files?

### CODE REVIEW

**Comment by langner** [comment]
> Question: what should the copyright years be on our source code files?

I don't know really, and I'm not sure if it matters much. I generally just try to update years with the current year when I edit a file.

**Comment by langner** [comment]
@berquist Is it possible to get QChem to print all MO coefficients?

**Comment by berquist** [comment]
Yes, but not consistently. I've been extracting the coefficients from both places they appear, but only storing the ones from a block that that doesn't display them all (only the occupieds plus 5 virtuals) due to slightly higher precision. Let me change that.

Also, `aooverlaps` isn't implemented yet because I haven't gotten it into the main codebase. It'll probably be another month or two.

**Comment by langner** [comment]
> Yes, but not consistently. I've been extracting the coefficients from both places they appear, but only storing the ones from a block that that doesn't display them all (only the occupieds plus 5 virtuals) due to slightly higher precision. Let me change that.

Regardless, the convention has been to always have `mocoeffs` be the shape it should be (and is internally in the program). The coefficients that are missing can be replaced by zeroes (which might be good enough if they are not printed due to being very small) or nan as needed. The preference has varied with time. But at the very least, I think we should consistently provide and test for correct dimenions.

If getting all coefficients requires special input options, that's fine; we should document those in the data notes for various programs.

**Comment by berquist** [comment]
@langner, I've merged your changes in.

**Comment by langner** [comment]
Great! Everything looks ready.

**Comment by ATenderholt** [comment]
Just noticed that ```aonames``` from QChem doesn't enumerate orbitals like other parsers:

```
adam@mqair:~/cclib/data/QChem/basicQChem4.2$ ccget aonames dvb_sp.out 
Attempting to read dvb_sp.out
aonames:
[u'C1_S', u'C1_S', u'C1_PX', u'C1_PY', u'C1_PZ', u'C2_S', u'C2_S', u'C2_PX', u'C2_PY', u'C2_PZ', u'C3_S', u'C3_S', u'C3_PX', u'C3_PY', u'C3_PZ', u'C4_S', u'C4_S', u'C4_PX', u'C4_PY', u'C4_PZ', u'C5_S', u'C5_S', u'C5_PX', u'C5_PY', u'C5_PZ', u'C6_S', u'C6_S', u'C6_PX', u'C6_PY', u'C6_PZ', u'H7_S', u'H8_S', u'H9_S', u'H10_S', u'C11_S', u'C11_S', u'C11_PX', u'C11_PY', u'C11_PZ', u'C12_S', u'C12_S', u'C12_PX', u'C12_PY', u'C12_PZ', u'H13_S', u'H14_S', u'H15_S', u'C16_S', u'C16_S', u'C16_PX', u'C16_PY', u'C16_PZ', u'C17_S', u'C17_S', u'C17_PX', u'C17_PY', u'C17_PZ', u'H18_S', u'H19_S', u'H20_S']
```

And the Gaussian example:

```
adam@mqair:~/cclib/data/Gaussian/basicGaussian09$ ccget aonames dvb_sp.out 
Attempting to read dvb_sp.out
aonames:
[u'C1_1S', u'C1_2S', u'C1_2PX', u'C1_2PY', u'C1_2PZ', u'C2_1S', u'C2_2S', u'C2_2PX', u'C2_2PY', u'C2_2PZ', u'C3_1S', u'C3_2S', u'C3_2PX', u'C3_2PY', u'C3_2PZ', u'C4_1S', u'C4_2S', u'C4_2PX', u'C4_2PY', u'C4_2PZ', u'C5_1S', u'C5_2S', u'C5_2PX', u'C5_2PY', u'C5_2PZ', u'H6_1S', u'H7_1S', u'H8_1S', u'C9_1S', u'C9_2S', u'C9_2PX', u'C9_2PY', u'C9_2PZ', u'C10_1S', u'C10_2S', u'C10_2PX', u'C10_2PY', u'C10_2PZ', u'H11_1S', u'H12_1S', u'H13_1S', u'C14_1S', u'C14_2S', u'C14_2PX', u'C14_2PY', u'C14_2PZ', u'H15_1S', u'C16_1S', u'C16_2S', u'C16_2PX', u'C16_2PY', u'C16_2PZ', u'H17_1S', u'H18_1S', u'C19_1S', u'C19_2S', u'C19_2PX', u'C19_2PY', u'C19_2PZ', u'H20_1S']
```

Should this be fixed?

**Comment by langner** [comment]
Good point. The problem is that we don't test for that (created #184).

**Comment by berquist** [comment]
I thought I caught that one, but I missed it. I'll take care of that.

**Pull request merged**
