### PR TITLE
Fixed NameError in volume.py

### PR DESCRIPTION
**Pull request by gaursagar**
`File "volume.py", line 142, in getbfs`
`mymol = makepyquante(coords, [0 for x in coords])`
`NameError: global name 'makepyquante' is not defined
`

### CODE REVIEW

**Comment by gaursagar** [comment]
There isn't a test case. However, at the end of the file is the following example:

`

    vol = Volume( (-3.0,-6,-2.0), (3.0, 6, 2.0), spacing=(0.25,0.25,0.25) )
    wavefn = wavefunction(d.atomcoords[0], d.mocoeffs[0][d.homos[0]],
                          c.gbasis, vol)
    assert abs(wavefn.integrate())<1E-6 # not necessarily true for all wavefns
    assert abs(wavefn.integrate_square() - 1.00)<1E-3 #   true for all wavefns
    print(wavefn.integrate(), wavefn.integrate_square())

    vol = Volume( (-3.0,-6,-2.0), (3.0, 6, 2.0), spacing=(0.25,0.25,0.25) )
    frontierorbs = [d.mocoeffs[0][(d.homos[0]-3):(d.homos[0]+1)]]
    density = electrondensity(d.atomcoords[0], frontierorbs, c.gbasis, vol)
    assert abs(density.integrate()-8.00)<1E-2
    print("Combined Density of 4 Frontier orbitals=",density.integrate())
 `

which outputs,
` -4.19796499281e-17 0.99927998933
 Combined Density of 4 Frontier orbitals= 7.99398118017 `

Should I move this to a test file? Or do something else.

PS. The test is failing due to some error in curl. Checks are passing in my personal fork https://travis-ci.org/gaursagar/cclib.

**Comment by langner** [comment]
> There isn't a test case. However, at the end of the file is the following example:
> 
> `
> 
> vol = Volume( (-3.0,-6,-2.0), (3.0, 6, 2.0), spacing=(0.25,0.25,0.25) )
> wavefn = wavefunction(d.atomcoords[0], d.mocoeffs[0][d.homos[0]],
>                       c.gbasis, vol)
> assert abs(wavefn.integrate())<1E-6 # not necessarily true for all wavefns
> assert abs(wavefn.integrate_square() - 1.00)<1E-3 #   true for all wavefns
> print(wavefn.integrate(), wavefn.integrate_square())
> 
> vol = Volume( (-3.0,-6,-2.0), (3.0, 6, 2.0), spacing=(0.25,0.25,0.25) )
> frontierorbs = [d.mocoeffs[0][(d.homos[0]-3):(d.homos[0]+1)]]
> density = electrondensity(d.atomcoords[0], frontierorbs, c.gbasis, vol)
> assert abs(density.integrate()-8.00)<1E-2
> print("Combined Density of 4 Frontier orbitals=",density.integrate())
> `
> 
> which outputs,
> -4.19796499281e-17 0.99927998933 Combined Density of 4 Frontier orbitals= 7.99398118017
> 
> Should I move this to a test file? Or do something else.

Yes, this would be good to do, but maybe in a separate PR?

Here, just make sure to add a simple unit test for getbfs() so that this code path is covered and we know it remains fixed.

Also, could you squash your commits into one?

**Comment by gaursagar** [comment]
Due to PyQuante's dependency on `numpy.oldnumeric` (depricated after `numpy 1.9`), this fix would require more work.
Closing the PR for now.

**Comment by langner** [comment]
Wait, so does your change fix something?

As far as the bridge is concerned, we should probably think about moving to pyquante2: https://github.com/rpmuller/pyquante2

**Comment by gaursagar** [comment]
This fix was to resolve scope of a function makepyquante defined in
cclib2pyquante.

However, while making test files for Volume.py I ran into issues related to
deprication of numpy.oldnumeric.
I closed this for now, and would make a separate PR after resolving issues
related to deprecation of PyQuante.

**Pull request closed without merging**
