### PR TITLE
Check number of atoms before adding extra masses

### LINKED ISSUE #1080: Bug in Gaussian parser: len(data.atommasses) != len(data.atomnos)
Sometimes Gaussian (09 at least) reports multiple "**Isotopes and Nuclear Properties**". Since the current parser appends from _all_ occurring sections, this leads to more atomic masses being reported than the actual number of atoms:

```python
In [1]: from cclib import ccopen

In [2]: data = ccopen("AcO-_0.gau.out").parse()

In [3]: len(data.atommasses)
Out[3]: 14

In [4]: len(data.atomnos)
Out[4]: 7
```

The offending code section is:

https://github.com/cclib/cclib/blob/3254c02924016715f47f623a29277ec4a0178044/cclib/parser/gaussianparser.py#L558-L567

[Attached is an output example that triggers the bug (out.zip).](https://github.com/cclib/cclib/files/7549332/out.zip)

I'm using cclib version 1.7.1:

```python
In [5]: from cclib import __version__

In [6]: __version__
Out[6]: '1.7.1'
```

### PR DESCRIPTION
**Pull request by schneiderfelipe**
This is an attempt to fix #1080.

### CODE REVIEW

**Comment by schneiderfelipe** [comment]
@shivupa I only had time to take a look at it now 😆. Is the 2.x branch (https://github.com/cclib/cclib/tree/2.x) the one you talked about?

**Comment by shivupa** [comment]
No worries! Its the one in #1076  https://github.com/shivupa/cclib/tree/multifile

**Comment by berquist** [comment]
Something funny is going on with this PR now. @schneiderfelipe can you confirm that we want to go the multifile route and scrap this PR?

**Comment by schneiderfelipe** [comment]
> Something funny is going on with this PR now. @schneiderfelipe can you confirm that we want to go the multifile route and scrap this PR?

Yes, I think multifile/multijob is the way to go. This is an ugly hack.

**Pull request closed without merging**
