### PR TITLE
Psi4: update unit tests and handle UHF/ROHF

### PR DESCRIPTION
**Pull request by berquist**
This brings the parser up-to-date with Psi4 1.0.

- [x] Ready for review

### CODE REVIEW

**Comment by langner** [comment]
Can you put the beta logfile into the regression suite?

**Comment by langner** [comment]
So is this ready to go as well? Do we want to include it in v1.5?

Also - did we ever have more test logfiles for Psi3?

**Comment by berquist** [comment]
This is done.

There weren't more files for Psi3. I do have a copy but I'm not sure it's worth putting in much effort to support it, considering it's almost 10 years old.

**Comment by langner** [comment]
> This is done.

Great. I'll take one last look today and merge in.

> There weren't more files for Psi3. I do have a copy but I'm not sure it's worth putting in much effort to support it, considering it's almost 10 years old.

I see. There is a version in Debian/Ubuntu, so there might be some use in getting the files in (#319).

**Pull request merged**
