### PR TITLE
ORCA: handle all single-character delimiter lines for geometry opt

### LINKED ISSUE #750: ORCA parser issue PM3 output
I am getting this error:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-bc9f1b410f32> in <module>
      1 file = "C24H34F3N5O3.out"
----> 2 data = cclib.io.ccread(file)

~/git/cclib/cclib/io/ccio.py in ccread(source, *args, **kwargs)
    180             return log.read_cjson()
    181         else:
--> 182             return log.parse()
    183     else:
    184         if kwargs.get('verbose', None):

~/git/cclib/cclib/parser/logfileparser.py in parse(self, progress, fupdate, cupdate)
    327             #   in data._attrlist will be moved to final data object that is returned.
    328             try:
--> 329                 self.extract(inputfile, line)
    330             except StopIteration:
    331                 self.logger.error("Unexpectedly encountered end of logfile.")

~/git/cclib/cclib/parser/orcaparser.py in extract(self, inputfile, line)
    427             while list(set(line.strip())) != ["."]:
    428                 name = line[10:28].strip().lower()
--> 429                 value = float(line.split()[2])
    430                 target = float(line.split()[3])
    431                 names.append(name)

IndexError: list index out of range
```
When trying to read this file:

[C24H34F3N5O3.txt](https://github.com/cclib/cclib/files/3432610/C24H34F3N5O3.txt)

I also attached a screenshot so that you can see how this is reproduced. 

Screenshot from 2019-07-25 10-15-51

I will try to fix it myself but wondered if you had encountered this error before?

### PR DESCRIPTION
**Pull request by berquist**
Closes #750 

This needs to go in _before_ https://github.com/cclib/cclib-data/pull/116.

### CODE REVIEW

**Comment by langner** [comment]
Is the Travis failure related?

**Comment by muammar** [comment]
JFTR, I just tried this and it solves #750.

**Comment by shivupa** [comment]
Could you rebase this on master please.

**Comment by langner** [comment]
This should be able to make it in before I cut v1.6.2. @berquist can you rebase?

**Comment by berquist** [comment]
@langner This is good to go now.

**Pull request merged**
