### PR TITLE
documentation build fixes

### LINKED ISSUE #1154: Problems with documentation
Something wrong with documentation
- On verison 1.7 currently - not being published to GH pages?
- Coverage table not working on readthedocs (new generated version)

### PR DESCRIPTION
**Pull request by berquist**
Closes #1154

### CODE REVIEW

**Comment by berquist** [comment]
Psi4 is segfaulting in the container...

**Comment by langner** [comment]
> Psi4 is segfaulting in the container...

Can you tell if that is psi4-specific or due to interactions with cclib?

**Comment by berquist** [comment]
> > Psi4 is segfaulting in the container...
> 
> Can you tell if that is psi4-specific or due to interactions with cclib?

I just tried running it in the container locally (only for Python 3.7) and it segfaults. Something must have changed recently in the container autobuild and push to Docker Hub.

**Comment by shivupa** [comment]
Sorry I should have said something but it slipped my mind. Github autopauses workflows if the repo hasn't seen a recent commit. I had to manually reset the dockerbuild workflow.

That causes the images to refresh so we are just seeing this breakage.

The breakage for 3.7 is coming because the 3.7 psi4 image is no longer updated. https://anaconda.org/psi4/psi4/files

I can confirm 3.7 breaks locally but 3.8 works fine locally in the docker images that were built 6 days ago

**Comment by berquist** [comment]
> Sorry I should have said something but it slipped my mind. Github autopauses workflows if the repo hasn't seen a recent commit. I had to manually reset the dockerbuild workflow.
>
> That causes the images to refresh so we are just seeing this breakage.
>
> The breakage for 3.7 is coming because the 3.7 psi4 image is no longer updated. [anaconda.org/psi4/psi4/files](https://anaconda.org/psi4/psi4/files)
>
> I can confirm 3.7 breaks locally but 3.8 works fine locally in the docker images that were built 6 days ago

But there *is* an older Psi4 for 3.7 available there (1.5).  When I run

``` bash
conda create -n psi4_37 python=3.7 psi4
```
I get this output from conda:
```
Proceed ([y]/n)?

Preparing transaction: ...working... done
Verifying transaction: ...working... INFO conda.core.link:verify(245): [ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::llvm-openmp-14.0.4-he0ac6c6_0, defaults/linux-64::intel-openmp-2022.1.0-h9e868ea_3769
  path: 'lib/libiomp5.so'

, ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::llvm-openmp-14.0.4-he0ac6c6_0, defaults/linux-64::intel-openmp-2022.1.0-h9e868ea_3769
  path: 'lib/libomptarget.so'

]
done
<snip>

INFO conda.core.link:_execute_actions(771): ===> LINKING PACKAGE: defaults::intel-openmp-2022.1.0-h9e868ea_3769 <===
  prefix=/home/eric/.pyenv/versions/miniforge3-4.10.3-10/envs/psi4_37
  source=/home/eric/data/.conda_pkgs/intel-openmp-2022.1.0-h9e868ea_3769

INFO conda.gateways.disk.create:create_link(353): file exists, but clobbering: '/home/eric/.pyenv/versions/miniforge3-4.10.3-10/envs/psi4_37/lib/libiomp5.so'
INFO conda.gateways.disk.create:create_link(353): file exists, but clobbering: '/home/eric/.pyenv/versions/miniforge3-4.10.3-10/envs/psi4_37/lib/libomptarget.so'
```

and a simple calculation (LiH, HF/STO-3G) gets this far:

```
  ==> DirectJK: Integral-Direct J/K Matrices <==

    J tasked:                  Yes
    K tasked:                  Yes
    wK tasked:                  No
    Integrals threads:           1
    Screening Type:           CSAM
    Screening Cutoff:        1E-12
    Incremental Fock:           No

  Minimum eigenvalue in the overlap matrix is 3.8797943699E-01.
  Reciprocal condition number of the overlap matrix is 2.3712582235E-01.
    Using symmetric orthogonalization.

  ==> Pre-Iterations <==

  SCF Guess: Superposition of Atomic Densities via on-the-fly atomic UHF (no occupation information).
```

before the segfault:

```
[eric@osmium]$ psi4 LiH.in
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libgdma.so         00007FD0AE1060DC  for__signal_handl     Unknown  Unknown
libc.so.6          00007FD0B504DA00  Unknown               Unknown  Unknown
core.cpython-37m-  00007FD0B1D34DC9  Unknown               Unknown  Unknown
core.cpython-37m-  00007FD0B241118F  Unknown               Unknown  Unknown
core.cpython-37m-  00007FD0B142F266  Unknown               Unknown  Unknown
core.cpython-37m-  00007FD0B0E02753  Unknown               Unknown  Unknown
libiomp5.so        00007FD06BD55893  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00007FD06BCC9429  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00007FD06BC85425  __kmpc_fork_call      Unknown  Unknown
core.cpython-37m-  00007FD0B0E02C38  Unknown               Unknown  Unknown
core.cpython-37m-  00007FD0B0D90259  _ZN3psi8DFHelper1     Unknown  Unknown
<snip>
```

So it looks like a conda dependency resolution problem rather than a Psi4 problem.

**Comment by shivupa** [comment]
I couldn't identify which dependency this is so we can pin it. I am trying to roll back to a previous mambaforge base image.

**Comment by shivupa** [comment]
That seems like it wont work. We also will not be able to build from scratch since psi4 now needs >=3.8

**Comment by berquist** [comment]
> I couldn't identify which dependency this is so we can pin it. I am trying to roll back to a previous mambaforge base image.

Identifying it should be possible. Do you want me to try?

**Comment by shivupa** [comment]
Let me take another look tonight and if I can't get it I'll ask for help?

**Comment by shivupa** [comment]
Yeah I'd appreciate if you were able to take a look @berquist

**Comment by berquist** [comment]
I didn't realize that GitHub purged the action run logs for old (~6 months) runs, or that the conda package list is only printed in the cclib-ci repo runs, not also here. I have an old 3.7 env locally that used to work, so I'll try to roll back to a working revision and dump the `environment.yml` from that.

**Comment by berquist** [comment]
@shivupa Updates for just for 3.7 are in https://github.com/shivupa/cclib-ci/pull/8, then we can do:
- a PR here that removes Python 3.6
- a PR to cclib-ci that unifies all the Dockerfiles (via symlinks) and GHA workflow files (via a build matrix) with these updates for other Python versions

**Comment by berquist** [comment]
See https://github.com/shivupa/cclib-ci/pull/9

**Review by shivupa — APPROVED** [review]

**Pull request merged**
