### PR TITLE
Remove explicit indexing from DDEC6

### PR DESCRIPTION
**Pull request by berquist**

### CODE REVIEW

**Comment by langner** [comment]
Eric, will we be able to merge this in?

**Comment by langner** [comment]
> Yes, this PR is self-contained and working as-is.

Excellent. Could you, for reference, put in here a comparison of some timing before and after you change?

**Comment by berquist** [comment]
Yes, I’ll upload a summary of my profiles later today.

**Comment by berquist** [comment]
Profiling script:
``` python
from cclib.method import DDEC6, volume
from cclib.io import ccread

root = Path("/home/eric/development/forks/cclib_pr_review/test/method")
path_data = root / "co.out"
path_cube = root / "co.cube"

data = ccread(str(path_data))
vol = volume.read_from_cube(str(path_cube))
# location of "atoms.h5"
analysis = DDEC6(data, vol, str(root))
analysis.calculate()
```
Then run `python -m cProfile -o profile_ddec6_4.out profile_ddec6.py` for each commit.
Profiling analysis script:
``` python
import pstats

profile_numbers = (0, 1, 2, 3, 4)
for profile_number in profile_numbers:
    p = pstats.Stats(f"profile_ddec6_{profile_number}.out")
    p.strip_dirs().sort_stats(pstats.SortKey.CUMULATIVE).print_stats(20)
    p.strip_dirs().sort_stats(pstats.SortKey.TIME).print_stats(20)
    p.strip_dirs().sort_stats(pstats.SortKey.CALLS).print_stats(20)
```
Here are the total times after each commit:
| commit number | method modified               | total time (s) |
|---------------|-------------------------------|---------------:|
| baseline      |                               |        164.974 |
| 1             | `_integrate_from_radial`      |         62.593 |
| 2             | `calculate_reference_charges` |         26.511 |
| 3             | `condition_densities`         |         19.809 |
| 4             | `_update_rho_cond`            |          6.762 |

According to the three profile summaries below, the two most important things to further optimize are:
- Whatever happens at the top-level `calculate` method
- `_spherical_average_from_cartesian`, it's called many times and has the largest total time for all calls combined.

I started to work on both coming up with a bigger example (to get more accurate benchmarks) and rewriting `_spherical_average_from_cartesian` to not have a loop over radial points, but for the latter removing this loop causes memory usage to grow considerably (`grid_filter` becomes rank 4), giving an order of magnitude worse performance. (Also the answer's not quite right...)

```
Wed Sep  2 23:48:21 2020    profile_ddec6_4.out

         2501021 function calls (2460917 primitive calls) in 6.762 seconds

   Ordered by: cumulative time
   List reduced from 3522 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    993/1    0.003    0.000    6.763    6.763 {built-in method builtins.exec}
        1    0.003    0.003    6.763    6.763 profile_ddec6.py:1(<module>)
        1    0.002    0.002    5.906    5.906 ddec.py:100(calculate)
        2    0.977    0.489    2.981    1.490 ddec.py:257(calculate_reference_charges)
        4    0.061    0.015    2.039    0.510 ddec.py:463(_calculate_w_and_u)
       24    1.512    0.063    1.903    0.079 ddec.py:668(_spherical_average_from_cartesian)
        6    0.000    0.000    1.585    0.264 __init__.py:8(<module>)
6076/4505    0.111    0.000    1.303    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
     3670    1.039    0.000    1.039    0.000 {built-in method numpy.array}
       98    0.000    0.000    1.033    0.011 _asarray.py:86(asanyarray)
   1168/3    0.003    0.000    0.676    0.225 <frozen importlib._bootstrap>:978(_find_and_load)
   1168/3    0.003    0.000    0.676    0.225 <frozen importlib._bootstrap>:948(_find_and_load_unlocked)
    758/3    0.002    0.000    0.676    0.225 <frozen importlib._bootstrap>:663(_load_unlocked)
    639/3    0.001    0.000    0.676    0.225 <frozen importlib._bootstrap_external>:722(exec_module)
   1076/3    0.000    0.000    0.675    0.225 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
   479/13    0.001    0.000    0.648    0.050 {built-in method builtins.__import__}
  2861/97    0.002    0.000    0.647    0.007 <frozen importlib._bootstrap>:1009(_handle_fromlist)
        2    0.000    0.000    0.631    0.315 __init__.py:24(<module>)
        4    0.000    0.000    0.572    0.143 <__array_function__ internals>:2(argmin)
       11    0.000    0.000    0.572    0.052 fromnumeric.py:52(_wrapfunc)


Wed Sep  2 23:48:21 2020    profile_ddec6_4.out

         2501021 function calls (2460917 primitive calls) in 6.762 seconds

   Ordered by: internal time
   List reduced from 3522 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       24    1.512    0.063    1.903    0.079 ddec.py:668(_spherical_average_from_cartesian)
     3670    1.039    0.000    1.039    0.000 {built-in method numpy.array}
        2    0.977    0.489    2.981    1.490 ddec.py:257(calculate_reference_charges)
        4    0.572    0.143    0.572    0.143 {method 'argmin' of 'numpy.ndarray' objects}
     2163    0.481    0.000    0.481    0.000 {method 'reduce' of 'numpy.ufunc' objects}
  1351568    0.353    0.000    0.353    0.000 ddec.py:274(<genexpr>)
        1    0.188    0.188    0.451    0.451 ddec.py:322(condition_densities)
       84    0.135    0.002    0.401    0.005 ddec.py:657(_integrate_from_radial)
        2    0.124    0.062    0.164    0.082 ddec.py:435(_ya)
6076/4505    0.111    0.000    1.303    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
      101    0.103    0.001    0.190    0.002 volume.py:181(integrate)
   113/97    0.065    0.001    0.094    0.001 {built-in method _imp.create_dynamic}
        4    0.061    0.015    2.039    0.510 ddec.py:463(_calculate_w_and_u)
     2004    0.057    0.000    0.057    0.000 {built-in method numpy.core._multiarray_umath.count_nonzero}
      372    0.056    0.000    0.056    0.000 {method '__deepcopy__' of 'numpy.ndarray' objects}
      638    0.055    0.000    0.055    0.000 {built-in method marshal.loads}
     1091    0.051    0.000    0.053    0.000 sre_compile.py:276(_optimize_charset)
   119563    0.035    0.000    0.035    0.000 {method 'split' of 'str' objects}
        1    0.031    0.031    0.145    0.145 volume.py:383(read_from_cube)
        1    0.026    0.026    0.038    0.038 pybel.py:19(<module>)


Wed Sep  2 23:48:21 2020    profile_ddec6_4.out

         2501021 function calls (2460917 primitive calls) in 6.762 seconds

   Ordered by: call count
   List reduced from 3522 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  1351568    0.353    0.000    0.353    0.000 ddec.py:274(<genexpr>)
   119563    0.035    0.000    0.035    0.000 {method 'split' of 'str' objects}
   113249    0.007    0.000    0.008    0.000 {method 'extend' of 'list' objects}
    69634    0.004    0.000    0.004    0.000 {method 'lower' of 'str' objects}
    53072    0.008    0.000    0.008    0.000 {built-in method builtins.isinstance}
    49336    0.003    0.000    0.003    0.000 {method 'append' of 'list' objects}
    49329    0.004    0.000    0.004    0.000 {method 'get' of 'dict' objects}
41741/39301    0.003    0.000    0.004    0.000 {built-in method builtins.len}
    26808    0.002    0.000    0.002    0.000 {built-in method builtins.id}
    22104    0.002    0.000    0.002    0.000 {method 'rstrip' of 'str' objects}
    21968    0.005    0.000    0.006    0.000 {built-in method builtins.getattr}
    21071    0.006    0.000    0.006    0.000 sre_parse.py:233(__next)
18830/1242    0.015    0.000    0.089    0.000 copy.py:132(deepcopy)
    17726    0.003    0.000    0.008    0.000 sre_parse.py:254(get)
    15192    0.004    0.000    0.006    0.000 sre_parse.py:164(__getitem__)
    14983    0.001    0.000    0.001    0.000 copy.py:190(_deepcopy_atomic)
    11677    0.002    0.000    0.002    0.000 {built-in method builtins.setattr}
    11603    0.002    0.000    0.002    0.000 {method 'join' of 'str' objects}
10376/10370    0.003    0.000    0.003    0.000 {built-in method builtins.hasattr}
     9558    0.001    0.000    0.001    0.000 {method 'startswith' of 'str' objects}
```

**Review by shivupa — APPROVED** [review]

**Comment by shivupa** [comment]
This is incredible work! LGTM

**Pull request merged**
