### PR TITLE
Gaussian 09: 2D potential energy scan output file

### PR DESCRIPTION
**Pull request by joanwa**
contains 2 files, both are 2 dimensional 4x4 steps potential energy
scans. One has all steps converged, the other has a scan step where no
convergence was achieved, hence the new flag ‘optstatus’ gives for this
step status ‘3: OPT_UNCONVERGED’

### CODE REVIEW

**Comment by langner** [comment]
This is good, but it is really a regression. So could you add it to cclib/cclib-data?

**Comment by langner** [comment]
I'll try to get this into the regressions for v1.4

**Comment by langner** [comment]
I opened a pull request with these files (unpackages) in cclib/cclib-data#25 along with a regression check - I hope that's OK. Would be nice to have this in for v1.4.

**Comment by ATenderholt** [comment]
I've merged https://github.com/cclib/cclib-data/pull/25, so I'm closing this PR.

**Pull request closed without merging**
