### PR TITLE
fixing an issue in xyzwriter

### PR DESCRIPTION
**Pull request by pzarabadip**
Hi,
This PR aims to fix the #814.

### CODE REVIEW

**Comment by langner** [comment]
Thanks for the fix! Are you able to also add a unit test for this?

**Comment by pzarabadip** [comment]
Sure @langner 
I thought there are tests already in place for this. It may be a bit delayed from my side but it would quite helpful if you can point me to similar ones.

**Comment by langner** [comment]
> Sure @langner
> I thought there are tests already in place for this. It may be a bit delayed from my side but it would quite helpful if you can point me to similar ones.

The existing tests for this module are here: https://github.com/cclib/cclib/blob/master/test/io/testxyzwriter.py

It would be ideal if we could get a test that covers the case you're fixing with this PR.

**Comment by berquist** [comment]
@pzarabadip Poke.

**Comment by langner** [comment]
This was done in #989

**Pull request closed without merging**
