### PR TITLE
Gaussian zero-point correction

### PR DESCRIPTION
**Pull request by kuriba**
Parsing support for zero-point correction from Gaussian frequency calculations.

### CODE REVIEW

**Comment by langner** [comment]
@berquist Was there any previous discussion for this?

**Comment by shivupa** [comment]
Could you rebase this on master please.

**Comment by berquist** [comment]
@langner No, there was not. I think it's a good thing to have, and is in line with the other thermochemistry attributes.

One thing we could do, in addition to having it as a property, is calculate it as a sanity check after parsing. It's CodeCogsEqn
which is not expensive (a sum over all `vibfreqs`).

**Comment by berquist** [comment]
@kuriba Poke; can you fix the accidental typo in `data.py`, rebase on master, and fix the test? Something like
```diff
diff --git a/cclib/parser/data.py b/cclib/parser/data.py
index 49b093a1..63d53a29 100644
--- a/cclib/parser/data.py
+++ b/cclib/parser/data.py
@@ -160,7 +160,7 @@ class ccData(object):
        "vibfreqs":         Attribute(numpy.ndarray,    'frequencies',                 'vibrations'),
        "vibirs":           Attribute(numpy.ndarray,    'IR',                          'vibrations:intensities'),
        "vibramans":        Attribute(numpy.ndarray,    'raman',                       'vibrations:intensities'),
-       "vibsyms":          Attribute(list,             'vibration symmetry',          'vibrations'
+       "vibsyms":          Attribute(list,             'vibration symmetry',          'vibrations'),^M
        "zpve":             Attribute(float,            'zero-point correction',       'properties:energies')
     }

diff --git a/test/data/testvib.py b/test/data/testvib.py
index e2f2be93..51297340 100644
--- a/test/data/testvib.py
+++ b/test/data/testvib.py
@@ -71,7 +71,7 @@ class GaussianIRTest(GenericIRTest):
     zpve = 0.1771
     def testzeropointcorrection(self):
         """Is the zero-point correction correct?"""
-        self.assertAlmostEqual(self.data.zpve, zpve, delta=0.001)
+        self.assertAlmostEqual(self.data.zpve, self.zpve, delta=0.001)^M


 class JaguarIRTest(GenericIRTest):
```

**Comment by berquist** [comment]
@kuriba Poke again. This is a good addition that we'd like to have.

**Comment by langner** [comment]
It's been a while. Closing this and continuing work in #853.

**Pull request closed without merging**
