### PR TITLE
Fixes issue with dealing with reduced list of atoms

### PR DESCRIPTION
**Pull request by langner**
This is a rebased version of #866

### CODE REVIEW

**Comment by langner** [comment]
Hmm.. I restricted the code to scenarios where NQMF>0, because some unit tests were failing. I worry that this might not correspond to the initial edge case the original PR was supposed to cover. But, there is no reference regression logfile, so I'm comfortable doing this.

**Comment by shivupa** [comment]
Do we want to generate a regression test for this?

**Comment by langner** [comment]
> Do we want to generate a regression test for this?

I didn't plan to; if you have time, then that'd be great. Maybe @MDAddario can send one.

**Comment by MDAddario** [comment]
I unfortunately cannot provide a reference logfile. This is why I was unable to pursue the original PR. If ever I am able to get a sample logfile in the future I will update you accordingly.

**Pull request merged**
