### PR TITLE
CJSON Reader - Removal of cjsonHolder DS

### PR DESCRIPTION
**Pull request by Schamnad**
Highlights of the changes:

1. The reader has been hooked to the ccget script such that a user can parse a cclib attribute in the following way:
`ccget --json <attribute/attribute list> *.cjson`

To use the --list flag with any cjson file, the --json flag must also be provided. For. eg:
` ccget --json --list <attribute/attribute list> *.cjson `
without the --json flag, the --list flag will throw an error
 
2. The writers/ folder has been renamed to io/ as it contains both readers and writers
3. The CJSON reader class has not been implemented as a ccData type because it reads a cjson file and is not a log file
4. The changes have been locally tested along with the code change mentioned in cclib/cclib-data#39 . All regression test cases pass. Once this PR is merged, the above PR needs to be merged.
5. This PR contains a few commits referring to a cjsonHolder DS which was deemed superfluous and hence removed, if the repository owners wish not to pollute the commit history with a DS which doesn't exist in the end, then I can squash all commits related to cjsonHolder into one and create a new PR

### CODE REVIEW

**Comment by Schamnad** [comment]
The Travis-ci build is failing because of naming conflicts in the regressions.py file. 
A fix for this is provided here:
cclib/cclib-data#39

**Comment by berquist** [comment]
On Python 3, it also fails for an additional reason:

```
$ python test_io.py
Traceback (most recent call last):
  File "test_io.py", line 17, in <module>
    from testccio import *
  File "io/testccio.py", line 17, in <module>
    import StringIO
ImportError: No module named 'StringIO'
```

**Comment by langner** [comment]
> $ python test_io.py
> Traceback (most recent call last):
>   File "test_io.py", line 17, in <module>
>     from testccio import *
>   File "io/testccio.py", line 17, in <module>
>     import StringIO
> ImportError: No module named 'StringIO'

Use `io.StringIO`, which I believe is also available in py2.7.

**Comment by langner** [comment]
@Schamnad you also need to resolve merge conflicts here.

**Comment by Schamnad** [comment]
Before incorporating the latest commits, the regression tests were passing locally. Post syncing with the master, one regression test is failing:

```
 NWChem/NWChem6.0/hydrogen_atom_UHF_cc-pVDZ.out... test failed
Traceback (most recent call last):
  File "../data/regression/regression.py", line 1327, in main
    res = eval(funcname)(logfile)
  File "../data/regression/regression.py", line 513, in testNWChem_NWChem6_0_hydrogen_atom_UHF_cc_pVDZ_out
    assert logfile.data.homos[1] == 0
AssertionError
```
Investigating this issue.

**Comment by langner** [comment]
> Before incorporating the latest commits, the regression tests were passing locally. Post syncing with the master, one regression test is failing:
> 
>  NWChem/NWChem6.0/hydrogen_atom_UHF_cc-pVDZ.out... test failed
> Traceback (most recent call last):
>   File "../data/regression/regression.py", line 1327, in main
>     res = eval(funcname)(logfile)
>   File "../data/regression/regression.py", line 513, in testNWChem_NWChem6_0_hydrogen_atom_UHF_cc_pVDZ_out
>     assert logfile.data.homos[1] == 0
> AssertionError
> Investigating this issue.

Try updating your cclib-data repository, or running `regression_download.sh`.

**Comment by langner** [comment]
I think this is OK to merge, although there are still things to improve:
* add tests for the new CJSON stuff
* also use the DS in the CJSON writer (reader is nice and concise)

But I think this is getting too big. For the future please remember that smaller, incremental changes are much easier to get in.

Will merge in soon if no one protests...

**Comment by berquist** [comment]
I've read it and am fine with it.

**Comment by Schamnad** [comment]
The time attribute had been removed while previously resolving conflicts.
@langner After updating the regression tests, all tests provided in the test instructions passed succesfully.

**Pull request merged**
