### PR TITLE
tentative fix for issue #974

### PR DESCRIPTION
**Pull request by srtlg**
I needed a fix for issue #974, too.  Maybe this is acceptable?

### CODE REVIEW

**Review by berquist — CHANGES_REQUESTED** [review]
Yes, I think this is also much nicer than the original solution. Since we already have the regression files you submitted, and we're going to go right to Q-Chem 5.3 (https://github.com/cclib/cclib/issues/977), can you remove the 5.2 files here?

**Comment by BalticPinguin** [comment]
Obviously I was too slow writing my PR (which is mostly ready, but uses a less handy approach). :-)

**Comment by berquist** [comment]
The error has nothing to do with your PR, but has been fixed in `master`. Can you rebase?

**Comment by langner** [comment]
We're going to start releasing 1.7 - would be nice to get this in; would need to be in the next few days.

**Comment by langner** [comment]
> Yes, I think this is also much nicer than the original solution. Since we already have the regression files you submitted, and we're going to go right to Q-Chem 5.3 (#977), can you remove the 5.2 files here?

This was addressed. No way for me to mark as resolved, but I think it's fine to merge in.

**Pull request merged**
