### PR TITLE
install pyquante2 with Python 3 fixes

### PR DESCRIPTION
**Pull request by berquist**
My fork has some fixes that let us use pyquante2 with all new Python versions.

iodata is required by tests and wasn't being installed.

### CODE REVIEW

**Comment by langner** [comment]
Would we depend on your fork long term then?

**Comment by berquist** [comment]
I'm not sure why it didn't occur to me that we should put the fork under our org. I think I've fixed the pyquante2+Cython install problems, fixed the pyquante2 CI, and set up our fork properly.

**Comment by berquist** [comment]
For some reason pip (in the RTD build) is trying to install the Git dependencies (pyquante2) before *its* dependencies (Cython). We need Cython in our `requirements.txt` because the pyquante2 `setup.py` requires Cython to run.

**Comment by berquist** [comment]
> For some reason pip (in the RTD build) is trying to install the Git dependencies (pyquante2) before _its_ dependencies (Cython). We need Cython in our `requirements.txt` because the pyquante2 `setup.py` requires Cython to run.

Need a workaround for this behavior: https://pip.pypa.io/en/stable/cli/pip_install/#argument-handling

**Review by shivupa — APPROVED** [review]
Sorry about the delay Thanks LGTM. Thanks for putting the fork under cclib!

**Pull request merged**
