### PR TITLE
ORCA 4.1.x adds a new line in vibrational frequencies output (test data update)

### PR DESCRIPTION
**Pull request by schneiderfelipe**
This solves #705. The new line about the scaling factor breaks the present ORCA parser:

```
(...)
-----------------------
VIBRATIONAL FREQUENCIES
-----------------------

Scaling factor for frequencies =  1.000000000  (already applied!)

   0:         0.00 cm**-1
   1:         0.00 cm**-1
   2:         0.00 cm**-1
   3:         0.00 cm**-1
   4:         0.00 cm**-1
   5:         0.00 cm**-1
   6:       -97.00 cm**-1 ***imaginary mode***
(...)
```

This PR also adds a single test instance for ORCA 4.1.x. If it's OK, I can rerun and add all tests from ORCA 4.0 to 4.1.

### CODE REVIEW

**Comment by schneiderfelipe** [comment]
I updated it so that all test data is now updated to 4.1.x (work was based on PR #575).

**Comment by ATenderholt** [comment]
Thanks! I'm happy to merge it as is, even though the new test files don't follow the 'copy from old test files --> commit --> update for new version --> commit' steps.

What do @langner and @berquist think? Is it ok to not have history of the new test files this time?

**Comment by langner** [comment]
I'd say it's not too important, but @schneiderfelipe if you can manage to keep the history that would be preferable. I can also do it for you if it's too much trouble. Let me know.

Like Adam said, it's basically three steps:
1. `git gopy` the latest checked in logfiles to the new location.
2. Update the copied files with the new outputs.
3. (optional) move oldest test files over to regressions

**Comment by schneiderfelipe** [comment]
I moved regressions to cclib-data ([PR here](https://github.com/cclib/cclib-data/pull/108)).

**Comment by langner** [comment]
Looks great, thanks!

**Pull request merged**
