### PR TITLE
Fixing bug with two letter chemical symbols

### PR DESCRIPTION
**Pull request by amandadumi**
This is to address the issue in #942 . I'm not sure what the best approach is incorporating a test for this behavior would be. Any advice would be appreciated!

### CODE REVIEW

**Comment by berquist** [comment]
You should make a PR with the silicon atom output file to the cclib-data repo, and add a regression test in https://github.com/cclib/cclib/blob/master/test/regression.py. As for what goes in the test, since it's failing even on parsing the first line in the MO coefficient block, I'd probably check the exact value of a single element from that line.

**Comment by langner** [comment]
> and add a regression test in https://github.com/cclib/cclib/blob/master/test/regression.py. As for what goes in the test, since it's failing even on parsing the first line in the MO coefficient block, I'd probably check the exact value of a single element from that line.

This is the last bit missing for this.

**Comment by amandadumi** [comment]
This should be good to go! Let me know if there are any issues I've overlooked or if you want the test to check anything else.

**Comment by langner** [comment]
Thanks! Looks good at a glance - I think cclib/cclib-data#137 needs to go in first.

**Review by langner — APPROVED** [review]

**Review by berquist — APPROVED** [review]

**Pull request merged**
