### PR TITLE
Travis CI: bump Python 3.6 -> 3.7

### PR DESCRIPTION
**Pull request by berquist**

### CODE REVIEW

**Comment by ATenderholt** [comment]
Travis failed. Looks unrelated to the change though, so I'll restart it.

**Comment by berquist** [comment]
From https://travis-ci.org/berquist/cclib/jobs/484653433,
```
collecting ... Fatal Python error: Segmentation fault
Current thread 0x00007f48fb6c4700 (most recent call first):
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/pybel.py", line 73 in <listcomp>
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/pybel.py", line 73 in _getplugins
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/pybel.py", line 96 in <module>
```
It's appearing on every Python version because I had to update from Trusty (14.04 LTS) to Xenial (16.04 LTS). This must come from one of the Open Babel shared libraries. It persists after clearing the Travis cache, which I'd guess means it isn't the library generated by SWIG when doing `pip install openbabel`, and on the surface the Ubuntu-packaged libraries don't appear different:
```
Package libopenbabel-dev

    trusty (14.04LTS) (libdevel): Chemical toolbox library (development files) [universe]
    2.3.2+dfsg-1.1: amd64 arm64 armhf i386 powerpc ppc64el
    xenial (16.04LTS) (libdevel): Chemical toolbox library (development files) [universe]
    2.3.2+dfsg-2.2build1: amd64 arm64 armhf i386 powerpc ppc64el s390x
```

**Comment by berquist** [comment]
I am going to ask the folks for debug access, because I'm not sure I could reproduce this in a Xenial Docker: https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by langner** [comment]
Eric, I've seen similar issues with pybel on my workstation. Can you try jumping over it to bionic (18.04)?

**Comment by berquist** [comment]
Thanks for the poke. I'll try again when I write up Docker notes, but IIRC it failed on Bionic too.

**Comment by berquist** [comment]
This was actually fixed by https://github.com/cclib/cclib/pull/760.

**Pull request merged**
