### PR TITLE
Switch from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by shivupa**
This is an attempt at adding github actions

### CODE REVIEW

**Comment by langner** [comment]
How do we now this works?

**Comment by shivupa** [comment]
Sorry I should have labeled this as WIP. I am still working on figuring out if everything is going to work right/if we can activate the actions for this PR

**Comment by shivupa** [comment]
(Testing locally with [act](https://github.com/nektos/act))

**Comment by ghutchis** [comment]
There should be workflow results at https://github.com/shivupa/cclib/actions 
(e.g., https://github.com/ghutchis/avogadrolibs/actions)

Try changing to:

`on: [push, pull_request]`

**Comment by berquist** [comment]
For now, I would put everything you're sticking in `github_actions` into `.github` instead. We will need to (probably later)
- extract out the non-GitHub Actions specific parts and
- move the general parts to a non-hidden location with a better name. Having the test runners there doesn't make sense, since those are the scripts we use when testing locally as well, in the event that developers can't/don't want to use `act`.

**Comment by shivupa** [comment]
Thanks will do. Is this holding up the release? I am trying to troubleshoot still

**Comment by langner** [comment]
> Thanks will do. Is this holding up the release? I am trying to troubleshoot still

Nope, we can do this for the next one (1.7.1) I'm just swamped somewhat and went on staycation last week.

BTW, really happy to see this moving along.

**Comment by berquist** [comment]
If you see https://github.com/nektos/act/issues/418#issuecomment-727261137, I made https://hub.docker.com/repository/docker/berquist/ubuntu-builder that we can temporarily use locally via `act -P ubuntu-latest=berquist/ubuntu-builder`.

**Comment by shivupa** [comment]
Build is green, but the doc building isn't triggering. Should run according to https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows

**Comment by langner** [comment]
#1008 should help with the new ASE bridge failure

**Comment by langner** [comment]
Also created PR for your branch @shivupa - shivupa/cclib#4

**Comment by berquist** [comment]
I think this is finally ready for review. Codecov is working on the branch, and RTD is going to keep failing until its configuration file is in `master`.

**Pull request merged**
