### PR TITLE
Update ORCA unit tests to 4.2

### PR DESCRIPTION
**Pull request by shivupa**
It seems that things changed in ORCA 4.2. I updated the unit tests so we can see where things break.

### CODE REVIEW

**Comment by shivupa** [comment]
```
ERROR    ORCA /home/travis/build/cclib/cclib/data/ORCA/basicORCA4.2/dvb_ir.out:logfileparser.py:334 Unexpectedly encountered end of logfile.
ERROR    ORCA /home/travis/build/cclib/cclib/data/ORCA/basicORCA4.2/dvb_raman.out:logfileparser.py:334 Unexpectedly encountered end of logfile.
```

I am fairly certain these will be fixed by #784 and then the only thing that needs done is #785 so 3.4 isn't failing. (or change the requirements.txt temporarily.)

**Comment by berquist** [comment]
Yep, I rebased this PR on top of #784 and everything works.

**Comment by berquist** [comment]
@shivupa Can you make a PR that removes ORCA 4.0 from unit tests and adds them to regressions?

**Comment by shivupa** [comment]
@berquist done!

**Comment by berquist** [comment]
Thanks!

**Pull request merged**
