### PR TITLE
Update ROHF conventions

### PR DESCRIPTION
**Pull request by berquist**
See the discussion in https://github.com/cclib/cclib/issues/301. Update so that the hydrogen atom gives `data.homos == [0 None]`.
- [ ] Ready for review

### CODE REVIEW

**Comment by langner** [comment]
The tests generally look good now... just 2 failing regressions I think.

**Comment by berquist** [comment]
My work computer was turned off due to a power outage, it has a bunch of uncommitted work to turn `homos` back into an array, and I'm on vacation until the 3rd, so this will probably have to wait until then.

**Comment by langner** [comment]
That's fine. Have a good holiday break!

**Comment by langner** [comment]
As discussed in #301, can we change the type back to an array for compatibility and adjust the length accordingly? We can explain this in the docs for `homos` (http://cclib.github.io/data_notes.html#homos), where we never mention how long the array is, so this solution feels appropriate.

**Comment by langner** [comment]
Pushing back to v.1.5.3

**Comment by berquist** [comment]
This has been open for several years and weighs on my mind every time I get the chance to work on cclib stuff. Maybe there's some good stuff in here, but it's still unclear in https://github.com/cclib/cclib/issues/301 what we want to do. I'll keep the branch just in case.

**Comment by langner** [comment]
Thanks, Eric. I think it would be good to be more aggressive with closing stale PRs in the future. Nothing is lost if the branches stay around, and it'd be great to have a cleaner state.

**Pull request closed without merging**
