### PR TITLE
Adding skipforMolcas on all test methods

### PR DESCRIPTION
**Pull request by kunalsharma05**
Just adding the skipforParser decorator on the methods. These will be removed as we keep on adding more functionality to the parser.

### CODE REVIEW

**Comment by TDI-tenderholt** [comment]
Looks good to me so far. Will you create a separate PR for the test files?

**Comment by kunalsharma05** [comment]
@TDI-tenderholt Yes, that's the plan.

**Comment by berquist** [comment]
Do we need this? Tests can simply not be added to the `testdata` file.

**Comment by ATenderholt** [comment]
The changes here were suggested by me (and maybe @langner) as a way to keep PRs small and targeting one change, while maintaining ability to merge directly into `master` without breaking the build. (This is almost like TDD, but instead of trying to fix failed tests, the skipped tests are being fixed.)

If tests are not added to `testdata` until that portion of the code is written, there's a chance that the PR will become fairly large before the tests pass. As a concrete example, there are 25 test cases in `testSP`. I think the current parser in #514 would fail in multiple places (`testcharge_and_mult`: no `mult`, `test_homos`: no `homos`, `testscftargetdim`: no `scftargets`, etc.).

**Comment by langner** [comment]
Merging this in...

I think in the long run it would be nice to get rid of the `testdata` file altogether, and do some combination of logfile discovery and annotating the test cases even more. Keeping all the information about a test case in one place is probably a good thing. I don't know if all the skips need to be added at once, but it doesn't hurt.

**Pull request merged**
