### PR TITLE
Dynamically set attribute and coverage column widths

### LINKED ISSUE #969: Documentation Issues
Hello! A few small things have gone awry with the docs on the github.io page.

Two examples I've noticed so far:
1.) The parsed data table formatting at: https://cclib.github.io/data.html. with "Couldn’t find cython becke routine" being printed right before the table should begin.
2.) Search functionality. Specifically, when i search anything, I get the expected search results, though when I click them they return a "page not found" error. 

 I will try to take a look, I'm not as familiar with the docs generation for cclib. It may be a quick fix that is obvious to someone else.

### PR DESCRIPTION
**Pull request by berquist**
Closes #969 

Adding `dispersionenergies` outgrew the fixed column widths, so this determines the width of each column based on the maximum width of each possible column.

### CODE REVIEW

**Review by shivupa — COMMENTED** [review]
Thanks for sorting this. Did the docs build locally?

**Comment by berquist** [comment]
Yes, but I haven’t actually looked at them, I will tomorrow morning.

**Review by shivupa — APPROVED** [review]
This works for me locally. I made a PR that makes it fill the page. That's an optional PR. This is good to go as is.

**Review by langner — APPROVED** [review]

**Comment by langner** [comment]
Thanks for this - not merging, since Eric probably wants to pull in Shiv's bit.

**Comment by berquist** [comment]
Still trying to remove `Couldn't find cython becke routine`...

**Comment by berquist** [comment]
Done. Made the above issue as a reminder to remove this part later.

**Comment by berquist** [comment]
This fails because I merged https://github.com/cclib/cclib-data/pull/147 but not https://github.com/cclib/cclib/pull/992.

**Pull request merged**
