### PR TITLE
Replace periodictable and SciPy with QCElemental

### LINKED ISSUE #776: Replace periodictable and SciPy with QCElemental
As discussed in https://github.com/cclib/cclib/issues/604, 

This would radically change library compatibility:
- Only Python >= 3.6 would be supported. Python 2 support would be dropped, which is perhaps ok, but 3.5 isn't EOL until September 2020 (https://devguide.python.org/#status-of-python-branches).
- Since Python 2 would be dropped, we can also drop `six`.
- Other old code can be dropped.
- It would bring in transitive dependencies on [`pint`](https://github.com/hgrecco/pint) and [`pydantic`](https://github.com/samuelcolvin/pydantic), neither of which have dependencies of their own. These are not as mature and stable as SciPy, though we wouldn't depend directly on their features. The physical constants might come with units attached, which could be nice.

I've set the milestone to 2.x, not because we want to wait a long time to do this, but because it's a breaking change in terms of Python support. We could finally use f-strings and type hints.

### PR DESCRIPTION
**Pull request by berquist**
Closes #776

### CODE REVIEW

**Comment by berquist** [comment]
Looks like tests run fine but the docs builds are failing, need to temporarily reinstall periodictable.

**Comment by shivupa** [comment]
The docs fail because of #766 right?

**Comment by berquist** [comment]
@shivupa Yes, but more specifically, the install dependencies are changing, which I wasn't considering in #766. To do that properly, once would need an additional isolated environment, probably for building the previous release.

**Comment by berquist** [comment]
Superseded by https://github.com/cclib/cclib/pull/972. In another PR, QCElemental will be used to replace periodictable, but we will keep SciPy as a hard dependency.

**Pull request closed without merging**
