### PR TITLE
Switch from unittest to pytest

### PR DESCRIPTION
**Pull request by berquist**
Closes https://github.com/cclib/cclib/issues/455.

There are still small annoyances, like not displaying the individual tests from `test_all`, and `test_regressions` showing as one test.

### CODE REVIEW

**Comment by langner** [comment]
Two questions:
1. Could you perhaps create separate issues for the bits you think should still be done?
2. Would it be feasible to publish the HTML output for coverage somewhere like cclib.github.io/coverage?

**Comment by berquist** [comment]
> Would it be feasible to publish the HTML output for coverage somewhere like cclib.github.io/coverage?

Yes, it just needs to get copied into the right place, and a link should be added in the docs. Should I do it for this PR?

**Comment by langner** [comment]
> > Would it be feasible to publish the HTML output for coverage somewhere like cclib.github.io/coverage?
> 
> Yes, it just needs to get copied into the right place, and a link should be added in the docs. Should I do it for this PR?

Sure, if it's not too much trouble.

**Comment by dgasmith** [comment]
Huge fan of `pytest`, things like parametrize and fixture really cut down on the amount of required code.

**Comment by langner** [comment]
> > > Would it be feasible to publish the HTML output for coverage somewhere like cclib.github.io/coverage?
> > 
> > 
> > Yes, it just needs to get copied into the right place, and a link should be added in the docs. Should I do it for this PR?
> 
> Sure, if it's not too much trouble.

I guess the doc generation process/script will take care of this, so I suppose we'll need to udpate it once this is submitted.

**Pull request merged**
