### PR TITLE
Turbomole: Added functionality to parse mpenergies and ccenergies

### PR DESCRIPTION
**Pull request by kunalsharma05**
And removed the relevant `testMP.py` tests.

Will remove the `ccenergies` tests as well from `testCC.py` on the CCSD files (#587) are merged.

### CODE REVIEW

**Comment by berquist** [comment]
@kunalsharma05 poke.

**Comment by ATenderholt** [comment]
Looks like it's still failing even though #570 was merged earlier. Also looks like there are conflicts, so maybe fixing those will have this PR pass?

**Comment by kunalsharma05** [comment]
Yup seems like it. Give me a minute to rebase.

**Comment by kunalsharma05** [comment]
Yup that fixes it.

**Pull request merged**
