### PR TITLE
Support and tests for parsing time from BOMD trajectories

### PR DESCRIPTION
**Pull request by berquist**
Adds further support for the `time` attribute, as outlined in https://github.com/cclib/cclib/issues/289.

* [ ] Ready to go

### CODE REVIEW

**Comment by langner** [comment]
I think it looks good to go once the unit tests are sorted out. Do we want to call the logfiles `dvb_md` instead of `dvb_bomd`, in case some program doesn't have BOMD?

**Comment by berquist** [comment]
I'm not sure how far you want to get into the weeds here, but some programs will do purely classical MD, some will do QM/MM MD, and some will do CPMD. They shouldn't look very different, but what we choose to have unit tests for in the future might require something more specific than `md`.

**Comment by langner** [comment]
> I'm not sure how far you want to get into the weeds here, but some programs will do purely classical MD, some will do QM/MM MD, and some will do CPMD. They shouldn't look very different, but what we choose to have unit tests for in the future might require something more specific than md.

I'm sure I understand your point. I'm just suggesting we name the file `dvb_md` but use whatever simplest method each program implements (but BOMD would be preferred).

**Comment by berquist** [comment]
Ok, sounds good.

**Comment by berquist** [comment]
Quick note that it is now impossible to read trajectories from ORCA 4.0; you can only print coordinates to trajectory-style XYZ files.

**Comment by langner** [comment]
Given the ongoing changes and merge conflicts with HEAD, I'm pushing this back to v1.5.3.

**Comment by langner** [comment]
> Quick note that it is now impossible to read trajectories from ORCA 4.0; you can only print coordinates to trajectory-style XYZ files.

OK, can we include this XYZ file with the outputs? We do support multifile outputs, so we can support this.

**Comment by berquist** [comment]
Good point. I'll get to that and try GAMESS within the next few days.

**Comment by berquist** [comment]
Reading from the main output (just includes times), the trajectory XYZ file, and another separate file where each SCF iteration is printed works for all important attributes except `atomcoords`. This is because

```
ORCA log file ['dvb_bomd.out', 'dvb_bomd-postrj.xyz', 'dvb_bomd.scf.log']
Identified logfile to be in ORCA format
```

which isn't entirely true. Is it possible to modify ccio to have fallback work for one file and be added to the combined `ccdata` correctly?

```python
from cclib.io import ccopen, ccread

filenames = [
    'dvb_bomd.out',
    'dvb_bomd-postrj.xyz',
    'dvb_bomd.scf.log',
]

# job = ccopen(filenames)
# print(job)
# data = job.parse()
data = ccread(filenames, verbose=True)

print('\n'.join(dir(data)))

import openbabel as ob
import pybel as pb
assert hasattr(data, 'atomcoords')
```

**Comment by berquist** [comment]
My current approach will be:

1. at the end of `ccopen`, if `is_listofstrings`, see if any can be opened by a fallback mechanism and parse them, returning a list of `ccdata`s
2. perform the "main" parse with `filetype(source, ...)` on the combined source
3. add all the `ccdata`s together by combining their attributes, starting with the fallback results so ours take priority, because the addition is not commutative

This could result in duplicate parsing, since there is overlap between the list of extensions provided by `pybel.informats.keys()` and our own classes.

**Comment by langner** [comment]
It's hard to grok this PR... there are a lot of changes and now conflicts with master. Could you separate this into a sequence of changes?

Ideally a PR should contain a single self-contained change.

**Comment by berquist** [comment]
This is now confusing. Cherry-picking the simplest things into a new PR.

**Pull request closed without merging**
