### PR TITLE
[ORCA] Fix for mocoeffs that are glued together (cclib/cclib#629)

### PR DESCRIPTION
**Pull request by langner**
This is a fix for #628, along with a regression test.

Needs to be submitted after cclib/cclib-data#92, should fail in Travis until that happens.

### CODE REVIEW

**Comment by ATenderholt** [comment]
What about a regex?  Something like `(-{0,1}\d+\.\d{6})` should work, assuming there is always 6 decimal places. Consume the string until no more matches are available.

**Comment by langner** [comment]
> What about a regex?  Something like `(-{0,1}\d+\.\d{6})` should work, assuming there is always 6 decimal places. Consume the string until no more matches are available.

Yes, that'll work. Done, and it's so short... genius!

**Comment by ATenderholt** [comment]
Looks like there's a problem with the conversion from regex `findall` results and converting to float: https://travis-ci.org/cclib/cclib/jobs/440163390#L682

Also, looks like there's an unrelated problem with the build for 2.7 (https://travis-ci.org/cclib/cclib/jobs/440163389#L583). Is `mock` part of `unittest` in 2.x?

**Comment by langner** [comment]
Thanks for pointing these out. I kinda assumed it would be OK because it was failing already...

> Looks like there's a problem with the conversion from regex `findall` results and converting to float: https://travis-ci.org/cclib/cclib/jobs/440163390#L682

Fixed by using a comprehension.

> Also, looks like there's an unrelated problem with the build for 2.7 (https://travis-ci.org/cclib/cclib/jobs/440163389#L583). Is `mock` part of `unittest` in 2.x?

I attempted to fix these thing in #631. So that should clear Travis, after which this PR should also be clean when I rebase it.

**Comment by langner** [comment]
... and cclib/cclib-data#92 also needs to be merged in first.

**Comment by berquist** [comment]
```
  File "/home/travis/build/cclib/cclib/cclib/parser/orcaparser.py", line 651, in extract
    mocoeffs[spin][i:i+len(coeffs), j] = map(float, coeffs)
TypeError: float() argument must be a string or a number, not 'map'
```

**Pull request merged**
