### PR TITLE
Add Benzeneselenol G09 input and output files to cclib_data

### PR DESCRIPTION
**Pull request by Schamnad**
Addition of these input/output files to create regression tests to check ccwrite's ability to write cjson output.

### CODE REVIEW

**Comment by langner** [comment]
I meant - could you add it to the cclib/cclib-data repository? It's specifically meant for regression tests.

**Comment by Schamnad** [comment]
Apologies, I didn't check the parent directory for the cclib-data repository. Will create a pull request there.

**Comment by ATenderholt** [comment]
Any opposition to closing this PR since these files should go into cclib-data?

**Comment by Schamnad** [comment]
You can go ahead and close it, I'll submit a PR in the right repo tomorrow
morning.
Away from the computer for now.

**Pull request closed without merging**
